---
title: "Explore Shiny+mrgsolve"
output: 
  flexdashboard::flex_dashboard:
    theme: united
runtime: shiny
---

```{r global}
library(mrgsolve)
library(dplyr)
library(shiny)
mod <- 
  mread_cache("irm1", modlib()) %>% 
  update(end=120,delta=0.25)
```


# Example {.sidebar}
```{r}
# Title: My Plot
# CL 0.2-2 by 0.2 start: 1
# VC 5-50 by 20 start: 5
# Select: linetype solid, dashed, dotted
# Select: dose 100 to 1000 by 100 start: 300
# Select: date
# Go button


```

# Server Tab 1

## Column 1

### Plot one

```{r}

# Is this a good idea?
renderPlot({
  
  e <- expand.ev(amt=100, ii=24, addl=2)  
  
  out <- 
    mod %>%
    data_set(e) %>%
    param(CL = 1, VC = 20) %>% 
    mrgsim(digits=3)
  
  plot(out,
       CP~.,
       main="My Plot",
       lty=1,
       xlab="Go / date")
})
```

### Table one

```{r}
renderTable({
  e <- expand.ev(amt=100, ii=24, addl=2)  
  
  out <- 
    mod %>%
    data_set(e) %>%
    param(CL = 1, VC = 20) %>% 
    mrgsim(digits=3)
  
  return(mrgsolve:::as.data.frame(head(out)))
})
```
